#include "./rest-capability.h"

#include "../src/validation/array-validator.h"
#include "../src/validation/number-validator.h"
#include "../src/validation/object-validator.h"
#include "../src/validation/pattern-validator.h"
#include "../src/validation/range-validator.h"
#include "../src/validation/validation-constraint.h"
#include "../src/validation/validation-entry.h"
#include "../src/validation/validation-result.h"
#include "../src/validation/validator.h"
#include "../src/validation/validators.h"
#include "../src/validation/value-type.h"
#include "../src/validation/value-validator.h"
